networks:
  caddy-network:
    name: caddy-network
    driver: overlay
    attachable: true
  private:
    driver: overlay
    attachable: true

volumes:
  caddy_data:

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
    networks:
      - caddy-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  api:
    labels:
      caddy: http://api.carful.localhost
