networks:
  caddy-network:
    external: true
    
  private:
    driver: overlay
    attachable: true

services:
  api:
    labels:
      caddy: api.carful.diy
  landing:
    labels:
      caddy: carful.diy
