services:
  api:
    image: ghcr.io/carful-diy/backend:latest
    env_file:
      - ../.env
    networks:
      - caddy-network
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    labels:
      caddy.reverse_proxy: "{{upstreams 80}}"